name: 'Update PR Branch'
description: 'Automatically update the branch of newest (by default) ready to merge PR. Designed to work with the auto-merge option.'
branding:
  icon: git-pull-request
  color: orange
inputs:
  base:
    required: true
    description: 'The base branch that this action will use to get PRs'
    default: 'master'
  direction:
    required: false
    description: 'The direction of the sort. Can be either `asc` or `desc`. Default: `desc` when `sort` is `created` or `sort` is not specified, otherwise `asc`.'
  required_approval_count:
    required: true
    description: 'The action will skip PRs that have less approvals than this value'
    default: '2'
  require_passed_checks:
    required: false
    description: 'If the action should skip PRs that have failed checks, defaults to `true`'
    default: 'true'
  require_auto_merge_enabled:
    required: false
    description: 'When set to false, the action includes PRs without auto-merge; the default true excludes such PRs.'
    default: 'true'
  sort:
    required: false
    description: 'What to sort results by. Can be either `created`, `updated`, `popularity` (comment count) or `long-running` (age, filtering by pulls updated in the last month).'
  token:
    description: 'The GitHub personal access token'
    required: true

runs:
  using: 'node20'
  main: 'dest/index.js'
